name: integration
on:
  pull_request:
    branches: [ main ]

jobs: 
  build-test: 
    runs-on: ubuntu-latest
    steps: 
      # git checkout 
      - name: checkout code
        uses: actions/checkout@v3
      
      # set up python version 
      - name: set up python 
        uses: actions/setup-python@v4
        with: 
          python-version: 3.8

      # install python dependencies 
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # run python linting
      - name: python linting
        run: pylint src/

      

      # run python unit tests 
      - name: python unit test 
        run: |
          cd src/
          export PYTHONPATH=`pwd`
          pytest